# Generated by Django 5.1.2 on 2024-10-23 11:57

import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='audiobook_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='USD da kiritamiz', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='shops.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='ebook_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='USD da kiritamiz', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='USD da kiritamiz', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='used_good_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='USD da kiritamiz', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='features',
            field=django_jsonform.models.fields.JSONField(),
        ),
    ]
