# Generated by Django 5.1.2 on 2024-10-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_rename_name_author_first_name_author_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
